apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      serviceAccountName: todo-app-service-account  # Attach ServiceAccount
      containers:
      - name: todo-app
        image: <your-dockerhub-username>/todo-list-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: AWS_REGION
          value: "eu-west-2"

