name: Cleanup Preview
on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup preview deployment
        run: |
          echo "Cleaning up preview for PR #${{ github.event.pull_request.number }}"
          # Add your cleanup commands here