name: Debug Token Authentication
on: workflow_dispatch
permissions:
  id-token: write
  contents: read
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::851725622142:role/GitHubActions-EKS-Role
          aws-region: eu-west-2

      - name: Debug Token
        run: |
          echo "🔍 Debugging EKS token..."
          
          # Generate token
          TOKEN_JSON=$(aws eks get-token --cluster-name Todo-list-App-cluster --region eu-west-2 --output json)
          TOKEN=$(echo "$TOKEN_JSON" | jq -r '.status.token')
          
          echo "Token length: ${#TOKEN}"
          echo "Token preview: ${TOKEN:0:100}..."
          
          # Decode the token to see what's inside
          echo "🔍 Decoding token payload..."
          PAYLOAD=$(echo "$TOKEN" | cut -d'.' -f2 | base64 -d 2>/dev/null | jq . 2>/dev/null || echo "Cannot decode token")
          echo "Token payload: $PAYLOAD"
          
          # Get cluster endpoint
          CLUSTER_ENDPOINT=$(aws eks describe-cluster --name Todo-list-App-cluster --region eu-west-2 --query "cluster.endpoint" --output text)
          
          echo "🔍 Testing direct API call with token..."
          curl -H "Authorization: Bearer $TOKEN" \
               "$CLUSTER_ENDPOINT/api/v1/nodes" \
               --insecure \
               -v \
               -w "\nHTTP Status: %{http_code}\n" \
               -o /tmp/response.txt
          
          echo "🔍 API Response:"
          cat /tmp/response.txt